# Generated by Django 2.2 on 2020-09-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='deleted',
        ),
    ]
