# Generated by Django 2.2 on 2020-09-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_remove_value_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
