# Generated by Django 2.2 on 2020-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0003_value_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schema',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
