# Generated by Django 2.2 on 2020-09-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_auto_20200905_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='reference',
        ),
        migrations.AddField(
            model_name='field',
            name='ref_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbapi.Field'),
        ),
    ]
