# Generated by Django 2.2 on 2020-09-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0005_auto_20200905_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='ref_id',
            field=models.ForeignKey(help_text='自关联字段', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbapi.Field'),
        ),
    ]
