# Generated by Django 2.2 on 2020-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0008_schema_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='test_date',
            field=models.DateTimeField(null=True),
        ),
    ]
