# Generated by Django 2.2 on 2020-09-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0010_auto_20200906_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
